name: Has linked issues

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]

jobs:
  check-linked-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Mock API Response (For Fork Testing)
        run: |
          echo '{ "issues": ["#123", "#456"] }' > mock_response.json
          cat mock_response.json
      
      - name: Simulate Issue Check
        run: |
          ISSUES=$(cat mock_response.json | jq -r '.issues | join(", ")')
          if [[ -z "$ISSUES" ]]; then
            echo "❌ No linked issues found."
            exit 1
          else
            echo "✅ Linked issues found: $ISSUES"
          fi
