name: Check linked issues

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  check_pull_requests:
    runs-on: ubuntu-latest
    name: Check linked issues
    permissions:
      issues: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - name: Get linked issues count
        run: |
          linked_issues_count=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open&labels=linked" | jq '. | length')
          echo "linked_issues_count=$linked_issues_count" >> $GITHUB_ENV
      - name: Output linked issues count
        run: echo "How many linked issues? ${{ env.linked_issues_count }}"
